name: Feature request
description: You have a brillant idea that you want to see added to pyRT_DISORT.
labels: enhancement

body:
  - type: textarea
    attributes:
      label: Feature request
      description: >-
        Please describe the feature you'd like to see added to pyrt.
        This may include papers, algorithms, code, etc.
    validations:
      required: true

  - type: input
    attributes:
      label: Priority
      description: >-
        How pressing is this issue?
    validations:
      required: true